### ISSUE TITLE
JDBCRunErrorPort needs update

### ISSUE THREAD

**Issue by just4li** [IBMStreams/streamsx.jdbc#68]
https://github.com/IBMStreams/streamsx.jdbc/blob/master/samples/JDBCSample/com.ibm.streamsx.jdbc.sample.jdbcrun/JDBCRunErrorPort.spl
CDISP0051E ERROR: An unknown attribute was specified: sqlMessage.

**Comment by anouri** [comment]
The Sample https://github.com/IBMStreams/streamsx.jdbc/blob/master/samples/JDBCSample/com.ibm.streamsx.jdbc.sample.jdbcrun/JDBCRunErrorPort.spl has been improved to grt the SQL code and SQL message:
Here is the result:
sqlCode: -803, 
sqlState: 23505 
sqlMessage One or more values in the INSERT statement, 
UPDATE statement, or foreign key update caused by a DELETE statement are not valid because the primary key, unique constraint or unique index identified by "1" constrains table 
"DB2INST1.JDBCRUN_ERRORPORT" from having duplicate values for the index key.. SQLCODE=-803, SQLSTATE=23505, DRIVER=4.16.53
